server:
  port: 8090

spring:
  application:
    name: audit-service

  datasource:
    url: jdbc:postgresql://localhost:5432/pgdb
    username: pguser
    password: pgpass
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update


spring-doc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html